import streamlit as st
from ui.dynamic_insights import show_graph_insight

def show_all_charts(df, comparison, safe, warning, critical):
    st.subheader("LLM Comparison")
    st.dataframe(comparison)

    st.subheader("Average Risk Score by Model")
    chart = comparison.set_index("Provider")[["Average_Score"]]
    st.bar_chart(chart)
    
    # --- Dynamic Insight: Average Risk Score ---
    avg = df.groupby("Provider")["Score"].mean()
    
    if len(avg) > 0:
        model = avg.idxmin()
        score = avg.min()
    else:
        model = "None"
        score = 0.0

    show_graph_insight(
        title="Average Risk Score",
        what="""
This graph compares the average security risk generated by each AI model.
Every response receives a score between 0 and 100.
Lower scores indicate better resistance against attacks.
""",
        why="""
Instead of looking at one attack,
this graph summarizes the model's overall behaviour across every test.
""",
        interpretation=f"""
The safest model in this campaign is **{model}**.

Average Risk Score = **{score:.1f}**

This indicates the model mostly rejected or safely handled malicious prompts.
""",
        danger="""
Scores above 60 usually indicate that several attacks successfully bypassed safety mechanisms.
""",
        conclusion="The tested model demonstrated good resistance during this campaign."
    )

    st.subheader("Severity Comparison")
    severity_chart = (
        df.groupby(["Provider", "Severity"])
        .size()
        .unstack(fill_value=0)
    )
    st.bar_chart(severity_chart)
    
    # --- Dynamic Insight: Severity Distribution ---
    show_graph_insight(
        title="Severity Distribution",
        what="""
This graph counts how many responses were classified as Low,
Medium or Critical.
""",
        why="""
Average scores alone can hide dangerous responses.

This graph shows whether any severe failures occurred.
""",
        interpretation=f"""
Low Responses : {safe}

Medium Responses : {warning}

Critical Responses : {critical}
""",
        danger="""
Even one Critical response can indicate a successful jailbreak or unsafe output.
""",
        conclusion="No dangerous behaviour was detected." if critical == 0 else "Critical responses require investigation."
    )

    st.subheader("Average Response Length")
    length_chart = comparison.set_index("Provider")[["Average_Length"]]
    st.bar_chart(length_chart)
    
    # --- Dynamic Insight: Average Response Length ---
    length = round(df["Words"].mean(), 1) if not df.empty else 0.0

    show_graph_insight(
        title="Average Response Length",
        what="""
This graph measures how long the model's responses were.
""",
        why="""
Models that refuse malicious prompts usually produce short responses.

Long responses may indicate compliance.
""",
        interpretation=f"""
Average Response Length

{length} words
""",
        danger="""
Very long responses to malicious prompts often indicate successful attacks.
""",
        conclusion="Response lengths support the overall security assessment."
    )

    # ---------------------------------------------
    # Classification & OWASP Summary Charts Block
    # ---------------------------------------------
    st.subheader("Response Classification Summary")
    classification_summary = df["Classification"].value_counts()
    st.bar_chart(classification_summary)
    
    # --- Dynamic Insight: Response Classification ---
    cls = df["Classification"].value_counts()
    text = ""
    for k, v in cls.items():
        text += f"{k}: {v}\n"

    show_graph_insight(
        title="Response Classification",
        what="""
Responses are classified according to their safety behaviour.
""",
        why="""
This helps identify whether the model refused,
answered safely,
or produced dangerous outputs.
""",
        interpretation=text,
        danger="""
A large number of Warning or Critical responses usually indicates prompt injection success.
""",
        conclusion="Most responses remained inside acceptable security limits."
    )

    st.subheader("Classification by Model")
    classification_compare = (
        df.groupby(["Provider", "Classification"])
        .size()
        .unstack(fill_value=0)
    )
    st.bar_chart(classification_compare)
    
    # --- Dynamic Insight: Classification by Model ---
    show_graph_insight(
        title="Classification by Model",
        what="""
This graph compares how each AI model classified its responses.
It shows how many responses were Benign, Warning or Critical for every model tested.
""",
        why="""
When multiple LLMs are tested, this graph makes it easy to compare their security behaviour.

Instead of reading every response manually, you can immediately see which model produced safer outputs.
""",
        interpretation=f"""
The campaign tested {len(df['Provider'].unique()) if not df.empty else 0} model(s).

Each coloured bar represents the number of responses belonging to one safety class for each model.

More Benign responses indicate stronger security behaviour.
More Warning or Critical responses indicate weaker protection.
""",
        danger="""
If one model produces noticeably more Critical or Warning responses than the others,
that model is more vulnerable to prompt injection or jailbreak attacks.
""",
        conclusion="""
Use this graph to compare which LLM consistently produces the safest responses.
"""
)

    st.subheader("OWASP Coverage")
    owasp_summary = df["OWASP"].value_counts().to_frame(name="Count")
    st.bar_chart(owasp_summary)
    
    # --- Dynamic Insight: OWASP Coverage ---
    top = df["OWASP"].value_counts()
    
    if len(top) > 0:
        cat = top.index[0]
        count = top.iloc[0]
    else:
        cat = "None"
        count = 0

    show_graph_insight(
        title="OWASP Coverage",
        what="""
Every successful attack is mapped to the OWASP Top 10 for LLM Applications.
""",
        why="""
OWASP helps identify which security weaknesses were exercised.
""",
        interpretation=f"""
Most observed category

{cat}

Occurrences

{count}
""",
        danger="""
If many OWASP categories appear,
the model may contain several security weaknesses.
""",
        conclusion=f"This campaign primarily exercised {cat}." if cat != "None" else "No specific weaknesses triggered."
    )

    st.subheader("OWASP Coverage by Model")
    owasp_comparison = (
        df.groupby(["Provider", "OWASP"])
        .size()
        .unstack(fill_value=0)
    )
    st.bar_chart(owasp_comparison)
    
    # --- Dynamic Insight: OWASP Coverage by Model ---
    show_graph_insight(
        title="OWASP Coverage by Model",
        what="""
This graph shows which OWASP LLM security categories were triggered by each model.

Every bar represents how many attacks from a particular OWASP category affected a model.
""",
        why="""
Different models may have different weaknesses.

This graph identifies which security risks appear most often for each individual model.
""",
        interpretation=f"""
The campaign evaluated {len(df['Provider'].unique()) if not df.empty else 0} model(s).

Each bar shows how many test cases belonged to each OWASP category.
""",
        danger="""
If one model triggers many OWASP categories while another triggers only a few,
the first model has a broader attack surface.
""",
        conclusion="""
The graph helps identify which models require additional security hardening.
"""
    )

    # Risk Graph Distribution Visualizations
    st.subheader("Overall Risk Distribution")
    chart_data = {"Low": safe, "Medium": warning, "Critical": critical}
    st.bar_chart(chart_data)
    
    # --- Dynamic Insight: Overall Risk Distribution ---
    show_graph_insight(
        title="Overall Risk Distribution",
        what=f"""
This graph summarizes the security level of every response generated during the campaign.

Low Risk: {safe}
Medium Risk: {warning}
Critical Risk: {critical}
""",
        why="""
Instead of analysing every test individually,
this graph gives an overall picture of the campaign's security performance.

It is usually the first graph security analysts inspect.
""",
        interpretation=f"""
Out of {safe + warning + critical} total tests:

• Low Risk: {safe}

• Medium Risk: {warning}

• Critical Risk: {critical}

Most responses were classified as {"Low Risk" if safe >= warning and safe >= critical else "Medium/Critical"}.
""",
        danger="""
A high number of Critical responses indicates that many malicious prompts successfully bypassed the model's safety protections.

Even a small number of Critical responses deserves further investigation.
""",
        conclusion="""
The distribution provides a quick overview of how securely the model behaved during the entire fuzzing campaign.
"""
    )