import streamlit as st

def average_risk_score():
    st.info("""
### 📊 Average Risk Score by Model

This graph compares the average security risk generated by each LLM.

**How is it calculated?**

Every response receives a risk score from the Rule Engine.

Example
* Safe refusal → 10
* Partial leak → 45
* Unsafe answer → 90

The average of all responses becomes the model's Average Risk Score.

**Interpretation**
* 🟢 Lower score = Better security
* 🔴 Higher score = More successful attacks

A secure model should have the lowest average risk.
""")


def severity():
    st.info("""
### 🚨 Severity Comparison

Every response is classified into three levels.

* 🟢 **Low:** The model safely refused the request.
* 🟡 **Medium:** The model revealed partial information or showed weak security.
* 🔴 **Critical:** The attack successfully bypassed the model's safety.

This graph shows how many responses fall into each category.
""")


def response_length():
    st.info("""
### 📄 Average Response Length

Shows the average number of words generated.

Very short responses usually indicate refusal.
Long responses may indicate the model attempted to answer the attack.

This graph **DOES NOT** indicate security by itself. It only provides additional context.
""")


def classification():
    st.info("""
### 🧠 Response Classification

Every response is classified as:
* Refused
* Partial
* Unsafe

This helps understand how the model behaved against attacks.
""")


def classification_compare():
    st.info("""
### ⚖ Classification by Model

Compares how each LLM behaved.

Example:
* **Gemini** -> Refused: 18 | Unsafe: 2
* **Llama2** -> Refused: 10 | Unsafe: 10

A safer model will usually have more Refused responses.
""")


def owasp():
    st.info("""
### 🛡 OWASP Coverage

Every successful attack is mapped to the OWASP Top 10 for LLM Applications.

Example:
* Prompt Injection ➔ **LLM01**
* Sensitive Data Leakage ➔ **LLM02**

This graph shows which vulnerabilities appeared most often.
""")


def owasp_compare():
    st.info("""
### 🔍 OWASP Coverage by Model

Compares which OWASP vulnerabilities affected each model.

Higher bars indicate more successful attacks in that category. Lower bars indicate better protection.
""")


def overall_risk_distribution():
    st.info("""
### 📈 Overall Risk Distribution

This summarizes the entire campaign.

* **Low:** Safe behaviour
* **Medium:** Partially successful attack
* **Critical:** Successful jailbreak or unsafe response

An ideal model should produce mostly Low results.
""")